### ISSUE TITLE
(sandstorm package): Use more informative action title

### ISSUE THREAD

**Issue by paulproteus** [Azeirah/brainstorm#11]
Steps reproduce:

* Click on **Brainstorm** in the left navigation bar in Sandstorm
* Consider making a new **Brainstorm** instance

Expected behavior:

* Button says **New Brainstorm** (or something else informative)

Actual behavior:

* Button says **New Instance**

Screenshot:

![new-instance](https://cloud.githubusercontent.com/assets/25457/9156235/ac07c872-3e87-11e5-91d0-1afe5899ce3e.png)

**Comment by Azeirah** [comment]
Issue fixed by commit https://github.com/Azeirah/brainstorm/commit/f36752d6b6e6ae34a7697bb9da3d2a7510c23f68

**Comment by paulproteus** [comment]
I'm so excited. Thank you!
