### ISSUE TITLE
New Brainstorm Graphics for Sandstorm Package

### ISSUE THREAD

**Issue by neynah** [Azeirah/brainstorm#13]
@Azeirah 

I'm Nena Nguyen, designer at Sandstorm. I'm reaching out to you about Brainstorm graphics because we're currently developing an app market and working on UI improvements to the existing Sandstorm shell design. See: https://groups.google.com/d/msg/sandstorm-dev/VRkPqX61cRs/Ts37SbqqKAAJ

As a part of this redesign, existing and new apps will need to submit 3 graphics (as a part of their SPK) for aesthetic and functional purposes.

I wasn't able to find any branding/logo assets for Brainstorm so I went ahead and designed you some graphics (inspired by your app's grid layout and a little green underscore highlight I saw).

If you think these are suitable, I can send you the files for when we need apps to update their SPKs(soonish). If not, I'll happily send over the illustrator/svg files or you can choose to come up with your own set.

Thanks!

:)

![brainstorm-preview1](https://cloud.githubusercontent.com/assets/855341/9238592/7b035af6-4108-11e5-9266-e826007e7596.png)

**Comment by Azeirah** [comment]
Hey @neynah, thanks a lot for these designs, I'm a terrible designer myself, which is why Brainstorm didn't have any icons before. If you could send me the design @ tijntje_7@msn.com, that would be wonderful.

Thanks!

**Comment by neynah** [comment]
@Azeirah You're very welcome. I'm glad you seem to like them. I just e-mailed the SVGs over. :)

**Comment by Azeirah** [comment]
Brainstorm is now a sandstorm.io application using these graphics.
Thanks @neynah, I'm closing this issue now.

I've added a thank you to the readme
