### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by somenxavier** [Azeirah/brainstorm#20]
The link; https://github.com/Azeirah/brainstorm#demo in readme file is not working. Can you fix it?

**Comment by Azeirah** [comment]
Fixed: https://github.com/Azeirah/brainstorm/pull/21

You can try the demo [on the sandstorm platform now](https://demo.sandstorm.io/appdemo/sptx6z162fp1w8rwe92vc8tzm76v0mk0wwc9yafze2vpghjs48j0)
